version: '3.9'
services:
  rasa:
    build: .
    image: rasa-chatbot-prototype
    container_name: rasa-chatbot-prototype
    ports:
      - "8099:5005"
    volumes:
      - ./models:/app/models
      - ./config:/app/config
      - ./data:/app/data
      - ./actions:/app/actions
      - ./endpoints.yml:/app/endpoints.yml
